pipeline {
    agent any
    
    // Aquí definimos tus variables del .env
    environment {
        // OJO: Lee la advertencia abajo sobre "localhost"
        API_SERVER_VAL = 'localhost' 
        API_PORT_VAL = '8090'
        KEYCLOAK_URL_VAL = 'http://localhost:9090'
        KEYCLOAK_REALM_VAL = 'toolrent-realm'
        KEYCLOAK_CLIENT_ID_VAL = 'toolrent-frontend'
    }

    stages{
        stage("Build and Push Docker Image"){
            steps{
                // Asegúrate que la ruta sea correcta donde está el Dockerfile
                dir("tingeso_frontend/tingeso_frontend"){ 
                    script{
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            // Usamos las variables de entorno en los build-args
                            sh """
                                docker build \
                                --build-arg VITE_API_SERVER=${API_SERVER_VAL} \
                                --build-arg VITE_API_PORT=${API_PORT_VAL} \
                                --build-arg VITE_KEYCLOAK_URL=${KEYCLOAK_URL_VAL} \
                                --build-arg VITE_KEYCLOAK_REALM=${KEYCLOAK_REALM_VAL} \
                                --build-arg VITE_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID_VAL} \
                                -t danielv28/tingeso_frontend .
                            """
                            
                            sh "docker push danielv28/tingeso_frontend"
                        }
                    }
                }
            }
        }
    }
}